### ISSUE TITLE
About obfs-server -r option

### ISSUE THREAD

**Issue by jerrylzy** [shadowsocks/simple-obfs#1]
I tried to use obfs-server but it only prints out usage information.
Then I ran this program in gdb and found that if `-r` option is not specified, this program will simply print out a usage message.

In /src/server.c, 
```C
// line 1127
        ...
        case 'r':
            dst_addr_str = optarg;
            break;
        ...

//  line 1234
    if (server_num == 0 || server_port == NULL || dst_addr_str == NULL) {
        usage();
        exit(EXIT_FAILURE);
    }
```
However, I didn't find any useful information in the man page. Also I can hardly tell what this option means from the usage string:

> -r <addr>:<port>           Forward traffic to this remote server address.

BTW, can I pair obfs-local with an older ss-libev on the client side? Like does the aforementioned combination work with the latest ss-libev with obfs enabled on the server side?

**Comment by madeye** [comment]
> However, I didn't find any useful information in the man page. Also I can hardly tell what this option means from the usage string

See the updated example section in the README

> BTW, can I pair obfs-local with an older ss-libev on the client side? 

Yes, you can.

> Like does the aforementioned combination work with the latest ss-libev with obfs enabled on the server side?

Yes, exactly.

**Comment by jerrylzy** [comment]
Thanks. It's working well with ss-server 2.6.0.
