### ISSUE TITLE
Can simple-obfs with --failover option handle non-obfuscated request from SS client?

### ISSUE THREAD

**Issue by denoza** [shadowsocks/simple-obfs#101]
I recently added a pull request on [streisand](https://github.com/jlund/streisand/pull/910) which adds the support of `--failover` option for SS-Libev server. Prior to this PR we had added the support for "Simple-Obfs" as an optional setting for Client. According to our tests, enabling Simple-Obfs on the Server side using the following options:

```
"plugin":"obfs-server",
"plugin_opts":"obfs=tls"
```
can route the SS traffic from client which chooses not to use Obfuscation. By adding the proper data in config.json, client has independence to route its traffic via Obfuscated tunnel or not. The [issue](https://github.com/jlund/streisand/pull/910#pullrequestreview-60473947) arose after adding the `failover` option in server config as follows:

```
"plugin":"obfs-server",
"plugin_opts":"obfs=tls;failover=127.0.0.1:xxx"
```
which is used to route the non-SS request to Nginx Webserver at port xxx. After this, client **must** use obfuscation otherwise the proxy doesn't work. My question is: is there something wrong with our setting for `failover` or the server using `failover` should only respond to obfuscated traffic?

**Comment by madeye** [comment]
> the server using failover should only respond to obfuscated traffic

Right, `failover` means any traffic that fails de-obfuscating should be redirected to Nginx. It helps to hide your traffic in real HTTP/TLS traffic.

**Comment by denoza** [comment]
@madeye Thank you for prompt response!

**Comment by denoza** [comment]
Closing the issue!
