### ISSUE TITLE
ss客户端的插件选项中obfs-host=www.bing.com

### ISSUE THREAD

**Issue by dragon100a** [shadowsocks/simple-obfs#109]
win10
ss客户端版本是4.0.6
vps 装好 obfs 后，
1.在ss服务器端端的配置文件里，
添加了 
"plugin":"obfs-server",
"plugin_opts":"obfs=http"
还需要添加其他内容 吗？

2.在ss客户端的“插件”  框 里 写的是 obfs-local（同时，ss客户端的目录里还需要有 cygwin1.dll和obfs-local.exe），
之后“插件选项” 框 里 写的是 obfs=http;obfs-host=www.bing.com
www.bing.com 也可以是别的地址？
obfs-host在客户端这边是不是必要的？

**Comment by ticonci** [comment]
1. 服务端不需要添加内容
2. 可以是其他地址；没有host的话，这个混淆就没有意义了。

**Comment by dragon100a** [comment]
@ticonci 
谢谢。
顺便一提，我还装了 fast open。我是这样操作的：
在 vps 那边，也就是服务器端
在/etc/sysctl.conf中添加net.ipv4.tcp_fastopen = 3
在/etc/shadowsocks-libev/config.json的大括号里，添加"fast_open": true,

现在回到win10下，ss的客户端配置文件里
    {
      "server": "*******",
      "server_port": *****,
      "password": "*******",
      "method": "aes-256-gcm",
      "plugin": "obfs-local",
      "plugin_opts": "obfs=http;obfs-host=www.bing.com",
      "remarks": "",
      "timeout": 5
    }

我还需要ss客户端的配置文件里 加 "fast_open": true,吗？

**Comment by dragon100a** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1402#issuecomment-331606580

**Comment by AmelieNet** [comment]
这个插件你是在哪里下载的?

**Comment by ticonci** [comment]
@AmelieNet https://github.com/imgk/simple-obfs-Cygwin/releases
