### ISSUE TITLE
simple-obfs-Cygwin/releases出现了新版？

### ISSUE THREAD

**Issue by dragon100a** [shadowsocks/simple-obfs#111]
https://github.com/imgk/simple-obfs-Cygwin/releases
昨天，20170926，出现了一个和上次不一样的版本，但版本号 没变，还是0.0.3

上次的版本是 我9月21日下载的，包含：
obfs-local.exe和cygwin1.dll

1.这次的版本是 obfs-local.exe和msys-2.0.dll，后者的dll是 cygwin1.dll的改名吗？
2.这次没改版本号，但 实质内容 有啥变化？
我需要把上周下载的 换成昨天的新发布的吗？

ps：https://github.com/imgk/simple-obfs-Cygwin 我没有找到issue按钮，没找到提问的地方，因此到这里来问了。。

**Comment by pexcn** [comment]
显然只是合并上游的修改

**Comment by AnyoeDove** [comment]
只是把cygwin编译的换成了msys2编译的 有什么大惊小怪的 自己把issue关了吧

**Comment by imgk** [comment]
换了电脑不想装 Cygwin，所以改用 MSYS2 编译的，合并了上游的修改，就这样

**Comment by pexcn** [comment]
@imgk 我发现用 MSYS2 编译的版本比 Cygwin 的版本速度快多了，之前试过 Cygwin 的版本，最快才 300 kb/s, 而这个可以到达 2 mb/s. (本地下载速度极限了。)

**Comment by dragon100a** [comment]
@imgk 概括起来就是9月26日，更换了编译工具，并重新编译了。
知道了。
