### ISSUE TITLE
obfs host 应该怎样使用？

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/simple-obfs#112]
```
obfs=tls;obfs-host=www.baidu.com
```
还是
```
obfs=tls;obfs_host=www.baidu.com
```
请问哪个会生效？

如果用 config 配置，是否应该用 `obfs_host` 而不是 `obfs-host` ?

**Comment by AnyoeDove** [comment]
https://github.com/shadowsocks/simple-obfs#plugin-mode-with-shadowsocks

**Comment by pexcn** [comment]
分别在什么情况下用 `obfs-host` 和 `obfs_host` ？

**Comment by AnyoeDove** [comment]
only obfs-host

**Comment by pexcn** [comment]
@AnyoeDove https://github.com/shadowsocks/simple-obfs/blob/master/src/jconf.c#L185 这行不识别 `obfs_host` 吗？

**Comment by AnyoeDove** [comment]
ask @madeye

**Comment by AnyoeDove** [comment]
https://github.com/imgk/simple-obfs-Cygwin#standalone-mode
oh i see
"obfs_host" only use in config file like this
```
{
"server": "1.2.3.4",
"server_port": 443,
"local_addr": "127.0.0.1",
"local_port": 12345,
"obfs": "tls",
"obfs_host": "a.com",
"timeout": 6
}
```

run 
> obfs-local -c ./config.json


>  2017-10-02 00:29:04 [simple-obfs] INFO: obfuscating enabled
> 2017-10-02 00:29:04 [simple-obfs] INFO: obfuscating hostname: a.com
>  2017-10-02 00:29:04 [simple-obfs] INFO: listening at 127.0.0.1:12345

**Comment by geekan** [comment]
a little confused here, should be better written in the doc

**Comment by AmelieNet** [comment]
@AnyoeDove 
```
{
"server": "1.2.3.4",
"server_port": 443,
"local_addr": "127.0.0.1",
"local_port": 12345,
"plugin":"obfs-local",
"plugin_opts":"obfs=tls;obfs-host=a.com",
"timeout": 6
}
```
难道不是这么设置吗?

**Comment by AnyoeDove** [comment]
two ways: [Plugin mode with shadowsocks](https://github.com/shadowsocks/simple-obfs/#plugin-mode-with-shadowsocks) and [Standalone mode](https://github.com/shadowsocks/simple-obfs/#standalone-mode)
u should read the [README.md](https://github.com/shadowsocks/simple-obfs/blob/master/README.md) before asking questions.

@pexcn problem solved. close issue?

**Comment by xiaoxing598** [comment]
@AnyoeDove `obfs-host` What exactly does that mean? How should I set it up? The document is not clearly written
