### ISSUE TITLE
is it  support for ss 2.6.1?

### ISSUE THREAD

**Issue by elric8** [shadowsocks/simple-obfs#12]
shadowsocks 2.6.1 canceled obfs
simple-obfs work on ss 2.6.1 plugin mode?
how make it work?

**Comment by elric8** [comment]
root@elric8:~# ss-server -c /etc/config.json --plugin "obfs-server --obfs http"
 2017-01-09 21:45:51 INFO: plugin "obfs-server --obfs http" enabled
 2017-01-09 21:45:51 INFO: initializing ciphers... rc4-md5
 2017-01-09 21:45:51 INFO: tcp port reuse enabled
 2017-01-09 21:45:51 INFO: listening at 127.0.0.1:37573
 2017-01-09 21:45:51 INFO: running from root user
sh: 1: exec: obfs-server: not found
 2017-01-09 21:45:51 ERROR: plugin service exit unexpectedly

it seem not work

**Comment by Sherlock-Holo** [comment]
do you install the simple-obfs？if not, absolutely it doesn't work

**Comment by elric8** [comment]
@Sherlock-Holo 
apt-get install --no-install-recommends build-essential autoconf libtool libssl-dev libpcre3-dev asciidoc xmlto
it is not install？
how install ？plase tell me ,i'm not good at linux,thank u for relpy

**Comment by suikatomoki** [comment]
@elric8 
apt install git
git clone https://github.com/shadowsocks/simple-obfs.git
cd simple-obfs
./configure && make && make install

**Comment by matsuz** [comment]
You should compile and install simple-obfs from source, the project doesn't provide prebuild package for installation.

You can build the binary like this on ubuntu:
```bash
mkdir simple-obfs & cd simple-obfs
apt install --no-install-recommends build-essential autoconf libtool libssl-dev libpcre3-dev asciidoc xmlto
curl -sSL https://github.com/shadowsocks/simple-obfs/archive/master.tar.gz | tar -xz --strip-component=1
./configure
make & make install
```

**Comment by elric8** [comment]
@suikatomoki @matsuz
thank guys!

**Comment by Sherlock-Holo** [comment]
they have given you the answer😋
