### ISSUE TITLE
Question: What is the purpose and best use of the "Host" option for the client?

### ISSUE THREAD

**Issue by joshdrsfsg** [shadowsocks/simple-obfs#125]
I've been testing what's the best "obfs-host" options on my OpenWRT and Android clients.  Some questions:

1. What are valid host options? Is _any_ web server acceptable or should it be a search engine? The OpenWRT client defaults to bing.com and the Android client seems to default to cloudflare (or something like that)
2. Is the "host" accessed by the client or the server? I ask this because it would affect my choice of hosts. For example if my client is in China and my Server is in Japan I would either chose baidu.com for fast access from the client or I would chose yahoo.co.jp for fast access from Japan (assuming a search engine is required).

Thank you for your help. Your software is very good.

**Comment by tony1016** [comment]
It's for HTTP header which used to confuse the firewall

2017年10月23日 下午1:42，"Josh Dillon" <notifications@github.com>写道：

**Comment by joshdrsfsg** [comment]
Very good! Thank you Tony. I've switched my HOST settings now to show something less suspicious.  From my testing, it's better not to use Chinese websites like baidu.com or taobao.com as the host in the headers since it's unlikely that I would need to exit China to reach them.  It's better to use unblocked international sites in the headers, like **aliyun**.
