### ISSUE TITLE
failover works fine but ss cannot work

### ISSUE THREAD

**Issue by iSuecii** [shadowsocks/simple-obfs#131]
I have employed ss-libev on my server and I want to use obfs to make ss and my site share the same 443 port. I changed the apache configure file to listen at 8443.
I have run this "obfs-server -s 1.2.3.4 -p 443 --obfs tls -r 127.0.0.1:1080 --failover 127.0.0.1:8443" on my server, and failover works fine, I can access my site normally.
But since I changed the ss port at the client to 443, ss cannot work.

what I tried:
1. use local address and local port in the command line, which is 127.0.0.1:1080, no help
2. use server address and server port, which is 0.0.0.0:8388, no help
3. add plug in phrase in ss configure file, no help

how can I make it work?

**Comment by machsix** [comment]
how did you solve the problem?
