### ISSUE TITLE
Windows版本的二进制obfs-local无法启动

### ISSUE THREAD

**Issue by EXSERENS** [shadowsocks/simple-obfs#146]
作业系统为Windows 10 16299 x86_64
双击EXE/命令行启动会弹出以下错误提示：
```
---------------------------
obfs-local.exe - 应用程序错误
---------------------------
应用程序无法正常启动(0xc000007b)。请单击“确定”关闭应用程序。 
---------------------------
确定   
---------------------------
```

**Comment by OneSeven** [comment]
https://github.com/imgk/simple-obfs-Cygwin

**Comment by EXSERENS** [comment]
@OneSeven Thanks!

**Comment by madeye** [comment]
Try also download this file to the same folder of obfs-local.exe:

https://www.dllme.com/dll/files/libwinpthread_1_dll.html

**Comment by EXSERENS** [comment]
@madeye I have already downloaded this dll, still not work.

**Comment by madeye** [comment]
Try the new binary: https://github.com/shadowsocks/simple-obfs/releases/download/v0.0.5/obfs-local.zip

**Comment by changyp6** [comment]
@madeye Your build can work!
I also tried to build obfs-local by myself, but my binary always have page fault inside libev.
Could you tell me what's the libev version you used? And how you built you libev library?

**Comment by madeye** [comment]
@changyp6 Add the following lines to the beginning of `ev.c` before cross compiling:

```
#define EV_STANDALONE
#define EV_USE_SELECT 1
#define EV_SELECT_IS_WINSOCKET 1
```

**Comment by changyp6** [comment]
@madeye Thanks very much!! It's working!!

**Comment by EXSERENS** [comment]
@madeye new binary is work! Thanks!

**Comment by EXSERENS** [comment]
@madeye 

运行时提示obfs-local.exe已停止工作，错误提示如下：

Assertion failed!

Program: C:\Users\bhytw\Desktop\\Shadowsocks\obfs-local.exe
File: ev.c, Line 3870

Expression: ("libev: ev_io_start called with negative fd", fd >= 0)

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by easycoderwei** [comment]
> @madeye Thanks very much!! It's working!!

I try to compile libev library first with msys2(mingw), but faied.
After git clone libev, I execute commands
    bash autogen.sh
    bash configure --build=mingw64 --host=x86_64-w64-mingw32
    make
When I execute make, error occured ( ./libtool: line 1093: lib: command not found ):
    make  all-am
    make[1]: Entering directory '/mingw64/libev'
    /bin/sh ./libtool  --tag=CC   --mode=link x86_64-w64-mingw32-gcc  -g -O3 -version-info 4:0:0  -o 
    libev.la -rpath /usr/lib ev.lo event.lo
    libtool: link: warning: undefined symbols not allowed in x86_64-w64-mingw32 shared libraries
    libtool: link: rm -fr  .libs/libev.lax
    copying selected object files to avoid basename conflicts...
    libtool: link: lib -OUT:.libs/libev.lib ev.o event.o
    ./libtool: line 1093: lib: command not found
    make[1]: *** [Makefile:441: libev.la] Error 127
    make[1]: Leaving directory '/mingw64/libev'
    make: *** [Makefile:351: all] Error 2

How do you resolve the library libev on window?
Can you provide more information about compiling obfs-local, preferably including compilation steps.

**Comment by weijx1903** [comment]
@madeye  @changyp6Any advice would be appreciate

**Comment by weijx1903** [comment]
@madeye @changyp6Any advice would be appreciate

**Comment by easycoderwei** [comment]
@madeye @changyp6    Any advice would be appreciate.
