### ISSUE TITLE
failover导致下载文件速度变慢

### ISSUE THREAD

**Issue by summer-wu** [shadowsocks/simple-obfs#150]
在man文档中没有说明--failover的作用。在README中有提到，貌似是：不符合obfs协议就转发给这个ip。

我在standalone模式下，使用`--failover=example.com`会导致下载速度变慢。正常网页、油管视频都可以打开，并且速度和不加混淆一样。就是下载文件速度特别慢，只有10K/s。

**Comment by ticonci** [comment]
这个和failover没有关系哦

**Comment by summer-wu** [comment]
今天又测试了一下，好像`--failover weibo.com`不起作用，`--failover weibo.com:80`起作用。
