### ISSUE TITLE
下载中能否增加32位windows的obfs-local？ 

### ISSUE THREAD

**Issue by xiaojj** [shadowsocks/simple-obfs#151]
Release中的obfs-local是不是64位的？能不能加一个32位的？谢谢。

**Comment by DBLobster** [comment]
https://cokebar.info/archives/1988

**Comment by DBLobster** [comment]
https://github.com/imgk/simple-obfs-Cygwin/releases/

**Comment by xiaojj** [comment]
收到，谢谢。
