### ISSUE TITLE
obfs-host 参数的疑问

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/simple-obfs#162]
当 `obfs=http` 时，我用网易的域名来混淆，`obfs-host` 的参数应该写成 `obfs-host=163.com` 还是 `obfs-host=www.163.com` 呢？

**Comment by pexcn** [comment]
`obfs-host` 修改的是 HTTP 协议的 Host 字段吗？

**Comment by tony1016** [comment]
没有太大关系，但是用网易域名确指向一个国外IP的话，岂不是昭告天下？？

李翊
信息安全管理部 at 交通银行总行信息技术管理部
A 上海市浦东新区上丰路1111号
P 021-58589999-8937 M +8613817909374

E liy_192@bankcomm.com W. http://tonylee.name

**Comment by tony1016** [comment]
如果是HTTP方式，是的

李翊
信息安全管理部 at 交通银行总行信息技术管理部
A 上海市浦东新区上丰路1111号
P 021-58589999-8937 M +8613817909374

E liy_192@bankcomm.com W. http://tonylee.name

**Comment by pexcn** [comment]
@tony1016 还有个问题，当 `obfs=http` 时，我访问 https 网站的时候，也会被混淆成 http ?

**Comment by tony1016** [comment]
在你的本地客户端和服务器之间，是HTTP内嵌加密数据的，不知道你明白吗

李翊
信息安全管理部 at 交通银行总行信息技术管理部
A 上海市浦东新区上丰路1111号
P 021-58589999-8937 M +8613817909374

E liy_192@bankcomm.com W. http://tonylee.name

**Comment by tony1016** [comment]
在你的本地客户端和服务器之间，是HTTP内嵌加密数据的，不知道你明白吗

**Comment by pexcn** [comment]
就是如果不加混淆就是 `[ 一段数据 ]` 这样，加了混淆就是 `[ HTTP 混淆 [ 一段数据 ] ]` 这样？包裹起来？

**Comment by tony1016** [comment]
是的

2018年1月16日 下午4:00，"Max Witten" <notifications@github.com>写道：

**Comment by pexcn** [comment]
好的，感谢。
