### ISSUE TITLE
Obfs x ? 

### ISSUE THREAD

**Issue by postadelmaga** [shadowsocks/simple-obfs#166]
I cannot find this in the documentation/readme:
 -  Is this plugin using obfs 3 or 4 ?
 ( I am not sure if those number make sense here: tor uses these number and I know in china only obfs-4 is working fine )

**Comment by imsupernewstar** [comment]
obfs1,2,3 and 4 are made by the tor team and used only for tor. It is not a generic protocol and this shadowsocks implementation has nothing to do with it. If you want to find a tor analogy, it's more like tor+meek

**Comment by postadelmaga** [comment]
ok thanks
