### ISSUE TITLE
Support `SS_PLUGIN_OPTIONS`

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/simple-obfs#17]
This is required so that I can continue working on: https://github.com/shadowsocks/shadowsocks-android/issues/1073

**Comment by madeye** [comment]
Please try 152b7d1

**Comment by Mygod** [comment]
Should we put Android client in this repo or a new repo?

**Comment by madeye** [comment]
I think a new repo is better as it will contain platform dependent code.

**Comment by Mygod** [comment]
Close this for now.
