### ISSUE TITLE
How exactly does the TLS handshake imitation and failover work?

### ISSUE THREAD

**Issue by cbeuw** [shadowsocks/simple-obfs#170]
I tried searching for docs but there aren't any. I could have probably figured this out myself by messing around with Wireshark but I'd still like to leave this issue here as a record.

So the questions are:
1. At which stage of the TLS handshake can the obfs server determine that the incoming request is from an SS client instead of a normal browser? (I have to assume the answer to this is clientHello because the failover mode would pass the request to a web server, hence the first request has to be a clientHello, otherwise the client will get TLS handshake failure)
2. What makes the difference between an SS client 
obfuscated request and a normal TLS handshake from a browser? 
3. Is there any mechanism in place that prevents the replay attack of resending the TLS handshake message and identifying the SS server behind simple-obfs?

**Comment by tony1016** [comment]
It's not a fully handshake,TLS tickets instead

2018年1月31日 上午7:46，"Qian Wang" <notifications@github.com>写道：

**Comment by imsupernewstar** [comment]
I had a look at obfs_tls.c and I saw the code for the TLS extension message, but I didn't see the generation of the ticket itself. Also in check_tls_request function, the only verification is for 6 constant bytes. Is that the only thing which differs shadowsocks from normal traffic?
