### ISSUE TITLE
simple-obfs in plugin mode does not work on port 80/443

### ISSUE THREAD

**Issue by firestorm99** [shadowsocks/simple-obfs#179]
I'd like to have my shadowsocks with simple-obs accessible on port 443 for the client, but if use port 80 oder 443 I can't connect with the client (no webserver running on the host). 

shadowsocks-libev 3.1.3
simple-obfs 0.0.5

Can anyone give me a hint?

Thanks a lot!

Logfile: 
Start with port 4443 (connected successfully): 
> Feb 23 19:58:56 vps ss-server[17278]:  2018-02-23 19:56:45 INFO: using tcp fast open
> Feb 23 19:58:56 vps ss-server[17278]:  2018-02-23 19:56:45 INFO: plugin "obfs-server" enabled
> Feb 23 19:58:56 vps ss-server[17278]:  2018-02-23 19:56:45 INFO: UDP relay enabled
> Feb 23 19:58:56 vps ss-server[17278]:  2018-02-23 19:56:45 INFO: initializing ciphers... chacha20-ietf-poly1305
> Feb 23 19:58:56 vps ss-server[17278]:  2018-02-23 19:56:45 INFO: tcp server listening at 127.0.0.1:36347
> Feb 23 19:58:56 vps ss-server[17278]:  2018-02-23 19:56:45 INFO: udp server listening at 0.0.0.0:4443

Start with port 443 (no connection possible): 
> Feb 23 19:58:58 vps systemd[1]: Started Shadowsocks-libev Default Server Service.
> Feb 23 19:58:58 vps ss-server[17356]:  2018-02-23 19:58:58 [simple-obfs] INFO: obfuscating enabled
> Feb 23 19:58:58 vps ss-server[17356]:  2018-02-23 19:58:58 [simple-obfs] INFO: tcp port reuse enabled
> Feb 23 19:58:58 vps ss-server[17356]:  2018-02-23 19:58:58 [simple-obfs] ERROR: bind: Permission denied
> Feb 23 19:58:58 vps ss-server[17356]:  2018-02-23 19:58:58 [simple-obfs] ERROR: Could not bind
> Feb 23 19:58:58 vps ss-server[17356]:  2018-02-23 19:58:58 [simple-obfs] ERROR: bind() error
> Feb 23 19:58:58 vps ss-server[17356]:  2018-02-23 19:58:58 ERROR: plugin service exit unexpectedly
> Feb 23 19:58:58 vps ss-server[17356]:  2018-02-23 19:58:58 INFO: using tcp fast open
> Feb 23 19:58:58 vps ss-server[17356]:  2018-02-23 19:58:58 INFO: plugin "obfs-server" enabled
> Feb 23 19:58:58 vps ss-server[17356]:  2018-02-23 19:58:58 INFO: UDP relay enabled
> Feb 23 19:58:58 vps ss-server[17356]:  2018-02-23 19:58:58 INFO: initializing ciphers... chacha20-ietf-poly1305
> Feb 23 19:58:58 vps ss-server[17356]:  2018-02-23 19:58:58 INFO: tcp server listening at 127.0.0.1:52635
> Feb 23 19:58:58 vps ss-server[17356]:  2018-02-23 19:58:58 INFO: udp server listening at 0.0.0.0:443

Shadowsocks config: 

> {
> "server":"0.0.0.0",
> "server_port":4443,
> "local_port":1080,
> "password":"xxx",
> "timeout":60,
> "method":"chacha20-ietf-poly1305",
> "fast_open":true,
> "verbose":1,
> "plugin":"obfs-server",
> "plugin_opts":"obfs=tls;fast-open,v"
> }

**Comment by firestorm99** [comment]
Could solve this on my own. It has to with the situation that no unprivileged daemon is allowed to run on ports <1024. 
I solved this using iptables: 
> iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 4443
> iptables -t nat -A PREROUTING -p udp --dport 443 -j REDIRECT --to-port 4443

issue can be closed.

**Comment by xcjiang** [comment]
you don't have to use iptables, just run this command:
sudo setcap 'cap_net_bind_service=+ep' /usr/local/bin/obfs-server
