### ISSUE TITLE
求standalone模式下的config配置文件的格式或者模板

### ISSUE THREAD

**Issue by zsbstephen** [shadowsocks/simple-obfs#182]
因为是用v2ray来搭建shadowsocks服务，故需要让obfs工作在standalone模式，并且服务器一开机就运行。因此参考了这个issue[https://gist.github.com/reallyimeric/07fd439d5a6607cf5f403f380864933a](url)
在/etc/systemd/system/obfs-server.service服务，obfs-server.service内容如下：
[Unit]
Description=Simple-obfs
After=network.target
Before=v2ray.service

[Service]
Type=simple-obfs
User=nobody
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
ExecStart=/usr/bin/obfs-server -c /etc/obfs-server/config.json

[Install]
WantedBy=multi-user.target

然后参照这个issus[https://github.com/shadowsocks/simple-obfs/issues/112](url)在etc路径下面创建obfs-server文件夹，并创建config.json文件，里面内容如下
{
"server": "0.0.0.0",
"server_port": 80,
"local_addr": "127.0.0.1",
"local_port": 8888,
"obfs": "http",
"obfs_host": "microsoft.com",
"timeout": 6
}

最后创建服务
sudo systemctl enable obfs-server
sudo systemctl daemon-reload
sudo systemctl restart obfs-server

然而服务启动个失败，手动启动obfs-server，出现下面的错误：
sudo obfs-server -c  /etc/obfs-server/config.json
[simple-obfs] ERROR: forwarding destination is not defined

因此只能上来求standalone模式下的config配置文件的格式或者模板了。

**Comment by debiansid** [comment]
-r你没有定义应该是

**Comment by zsbstephen** [comment]
经过群友的指点，终于解决了~正确的config.json格式如下：
{
 "server": "0.0.0.0",
 "server_port": 80,
 "dst_addr": "127.0.0.1:8888",
 "timeout": 60,
 "obfs": "http",
 "reuse_port": true,
 "fast_open": true
}

obfs-server.service的内容不变：
[Unit]
Description=Simple-obfs
After=network.target

[Service]
Type=simple-obfs
User=nobody
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
ExecStart=/usr/local/bin/obfs-server -c /etc/obfs-server/config.json

[Install]
WantedBy=multi-user.target

更新系统服务并启动，然而发现服务并没有在后台持续运行，经过群友指点，obfs-server.service启动并没有root权限，不能监听80端口，所以需要将obfs-server绑定到80端口，运行下面的命令：
setcap cap_net_bind_service=+ep /usr/local/bin/obfs-server
再重新restart一下obfs-server.service，搞定~

另外，google搜索到另一个方法，就是用修改/etc/rc.local文件，在最后的exit上面加这么一行命令
nohup /usr/bin/obfs-server -c /etc/obfs-server/obfs-server-config.json >/dev/null 2>&1 &
reboot重启服务器，ok大功告成~

**Comment by songzmwow** [comment]
我想知道下v2ray用ss的obfs的配置文件应该如何写？ 麻烦能指点下么？
