### ISSUE TITLE
Unable to connect after running for a period time

### ISSUE THREAD

**Issue by Unbinilium** [shadowsocks/simple-obfs#186]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

### What version of shadowsocks-libev are you using?
`ss-server` Build from release `v3.1.3`
`obfs-server` Build from commit `474158f`

### What operating system are you using?
`Debian 9` and `Linux 4.15.9-041509-lowlatency`

### What did you do?
`ss-server -u -c config.json`

### What did you expect to see?
Be able to connect and use normally any time

### What did you see instead?
- Cannot connect due to `time-out` error after a period normally using when `obfs-plugin` is on at client-side
- When it happens, turn off `obfs-plugin` on client side and now be able to connect again
- If not restart `ss-server` when it happend, client will never be able to connect with `obfs-plugin` again
- Self-test reproduced every time, tested on different `IP` or `obfs-host`, and no error log collected in `verbose` mode
- It seems a bug of `simple-obfs` but older version also has it reproduced
- Reproduces after abou 30 mins or it could be 6 hours, even longer
- Ita process still running when reproduce this issue checked by `ps -ef | grep obfs-server`

### What is your config in detail (with all sensitive info masked)?
- config.json
```
{
    "server":"["[::0]","0.0.0.0"]",
    "server_port":443,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"*****",
    "method":"xchacha20-ietf-poly1305",
    "timeout":600,
    "udp_timeout":600,
    "plugin":"obfs-server",
    "plugin_opts":"obfs=tls;fast-open;failover=cn.bing.com",
    "fast_open":true,
    "reuse_port":true,
    "nameserver":"8.8.8.8,8.8.4.4,2001:4860:4860::8888,2001:4860:4860::8844",
    "dscp":"EF",
    "mode":"tcp_and_udp",
    "ipv6_first":true,
    "no_delay":true,
}
```

**Comment by Unbinilium** [comment]
Seems caused by Kernel

**Comment by Unbinilium** [comment]
Reopen due to it reproduced again

**Comment by zhangciwu** [comment]
Same problem of obfs=tls
