### ISSUE TITLE
使用插件后，shadowsocks-android udp转发失效

### ISSUE THREAD

**Issue by eastmalon** [shadowsocks/simple-obfs#19]
服务端: shadowsocks-libev 2.6.2
客户端: shadowsocks-libev 2.6.2, shadowsocks-android 3.3.1 & 3.4.1

当使用服务端使用simple-obfs 插件（--plugin "obfs-server --obfs http"）时：shadowsocks-android 开启udp转发无法连接；但是shadowsocks-libev 可以使用-u并且连上。
当使用服务端不使用simple-obfs 插件时：两种客户端都能使用udp。

**Comment by suikatomoki** [comment]
android3.x还不支持混淆

**Comment by eastmalon** [comment]
@suikatomoki 这和支持混淆没关系吧，不开udp就能连上

**Comment by madeye** [comment]
Try https://github.com/shadowsocks/shadowsocks-libev/commit/0acc79b430b451cbcf50c8eec69c9f31ec551d1a

**Comment by eastmalon** [comment]
[shadowsocks/shadowsocks-libev@0acc79b](https://github.com/shadowsocks/shadowsocks-libev/commit/0acc79b430b451cbcf50c8eec69c9f31ec551d1a) 修复了这个问题
