### ISSUE TITLE
"fast-open" in --plugin-opts

### ISSUE THREAD

**Issue by maxduke** [shadowsocks/simple-obfs#228]
Currently I'm using Plugin mode and I've already specified "--fast-open" with ss-server and ss-local.
Then I found I can also specify "fast-open" in --plugin-opts. The question is shall I add "fast-open"  to "--plugin-opts" like --plugin-opts "obfs=http;failover=127.0.0.1:8080;fast-open"? 
For both server and client?

**Comment by kimw** [comment]
Yes, it is.

**Comment by maxduke** [comment]
发现如果服务器同时开启failover和fast-open的，且在客户端开启fast-open的话会产生大量
[simple-obfs] ERROR: remote_recv_cb_recv: Connection timed out
而且访问非常慢，有很大几率打不开，客户端去除fast-open，或服务器端不设置failover则正常，不知道是不是bug

**Comment by kimw** [comment]
1. The `failover` option is optional, but it's strongly commended. So, don't turn it off unless you do know what you're doing.

2. If you do really mind the log messages, try to -- turn off `tcp_fastopen` in `ss-server`, and keep `tcp_fastopen` on in `obfs-server` -- for performance reason.
