### ISSUE TITLE
编译安装报错

### ISSUE THREAD

**Issue by fhwo13** [shadowsocks/simple-obfs#231]
按照官方文档说明安装，在编译的时候make报错，麻烦大佬帮忙看看
OS: CentOS 6.10，python 2.6.6，ss-python版本

configure: creating ./config.status
config.status: creating doc/Makefile
config.status: creating Makefile
config.status: creating libcork/Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
make  all-recursive
make[1]: Entering directory `/root/simple-obfs'
Making all in libcork
make[2]: Entering directory `/root/simple-obfs/libcork'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/root/simple-obfs/libcork'
Making all in src
make[2]: Entering directory `/root/simple-obfs/src'
  CC     obfs_local-local.o
In file included from local.c:57:
local.h:26:16: error: ev.h: No such file or directory
In file included from local.c:57:
local.h:39: error: expected specifier-qualifier-list before ‘ev_io’
local.h:50: error: expected specifier-qualifier-list before ‘ev_io’
local.h:72: error: expected specifier-qualifier-list before ‘ev_io’
local.c:98: error: expected ‘)’ before ‘ev_io’
local.c:99: error: expected ‘)’ before ‘ev_io’
local.c:100: error: expected ‘)’ before ‘ev_io’
local.c:101: error: expected ‘)’ before ‘ev_io’
local.c:102: error: expected ‘)’ before ‘ev_io’
local.c:103: error: expected ‘)’ before ‘ev_signal’
local.c:111: error: expected ‘)’ before ‘remote_t’
local.c:113: error: expected ‘)’ before ‘server_t’
local.c:132: error: expected ‘)’ before ‘ev_timer’
cc1: warnings being treated as errors
local.c:233: error: ‘struct ev_loop’ declared inside parameter list
local.c:233: error: its scope is only this definition or declaration, which is probably not what you want
local.c: In function ‘free_connections’:
local.c:239: error: implicit declaration of function ‘close_and_free_server’
local.c:240: error: implicit declaration of function ‘close_and_free_remote’
local.c: At top level:
local.c:245: error: expected ‘)’ before ‘ev_io’
local.c:497: error: expected ‘)’ before ‘ev_io’
local.c:535: error: expected ‘)’ before ‘ev_timer’
local.c:552: error: expected ‘)’ before ‘ev_io’
local.c:627: error: expected ‘)’ before ‘ev_io’
local.c: In function ‘new_remote’:
local.c:735: error: ‘struct remote_ctx’ has no member named ‘connected’
local.c:736: error: ‘struct remote_ctx’ has no member named ‘connected’
local.c:738: error: ‘struct remote_ctx’ has no member named ‘remote’
local.c:739: error: ‘struct remote_ctx’ has no member named ‘remote’
local.c:741: error: implicit declaration of function ‘ev_io_init’
local.c:741: error: ‘struct remote_ctx’ has no member named ‘io’
local.c:741: error: ‘remote_recv_cb’ undeclared (first use in this function)
local.c:741: error: (Each undeclared identifier is reported only once
local.c:741: error: for each function it appears in.)
local.c:741: error: ‘EV_READ’ undeclared (first use in this function)
local.c:742: error: ‘struct remote_ctx’ has no member named ‘io’
local.c:742: error: ‘remote_send_cb’ undeclared (first use in this function)
local.c:742: error: ‘EV_WRITE’ undeclared (first use in this function)
local.c:743: error: implicit declaration of function ‘ev_timer_init’
local.c:743: error: ‘struct remote_ctx’ has no member named ‘watcher’
local.c:743: error: ‘remote_timeout_cb’ undeclared (first use in this function)
local.c:745: error: ‘struct remote_ctx’ has no member named ‘watcher’
local.c: At top level:
local.c:767: error: expected ‘)’ before ‘remote_t’
local.c: In function ‘new_server’:
local.c:794: error: ‘struct server_ctx’ has no member named ‘connected’
local.c:795: error: ‘struct server_ctx’ has no member named ‘connected’
local.c:797: error: ‘struct server_ctx’ has no member named ‘server’
local.c:798: error: ‘struct server_ctx’ has no member named ‘server’
local.c:805: error: ‘struct server_ctx’ has no member named ‘io’
local.c:805: error: ‘server_recv_cb’ undeclared (first use in this function)
local.c:805: error: ‘EV_READ’ undeclared (first use in this function)
local.c:806: error: ‘struct server_ctx’ has no member named ‘io’
local.c:806: error: ‘server_send_cb’ undeclared (first use in this function)
local.c:806: error: ‘EV_WRITE’ undeclared (first use in this function)
local.c: At top level:
local.c:837: error: expected ‘)’ before ‘server_t’
local.c: In function ‘create_remote’:
local.c:853: error: ‘listen_ctx_t’ has no member named ‘remote_num’
local.c:855: error: ‘listen_ctx_t’ has no member named ‘remote_addr’
local.c:873: error: ‘listen_ctx_t’ has no member named ‘mptcp’
local.c:883: error: ‘listen_ctx_t’ has no member named ‘iface’
local.c:884: error: ‘listen_ctx_t’ has no member named ‘iface’
local.c:889: error: ‘listen_ctx_t’ has no member named ‘timeout’
local.c: At top level:
local.c:897: error: expected ‘)’ before ‘ev_signal’
local.c:913: error: expected ‘)’ before ‘ev_io’
local.c: In function ‘main’:
local.c:1282: error: ‘listen_ctx_t’ has no member named ‘remote_num’
local.c:1283: error: ‘listen_ctx_t’ has no member named ‘remote_addr’
local.c:1284: error: ‘listen_ctx_t’ has no member named ‘remote_addr’
local.c:1294: error: ‘listen_ctx_t’ has no member named ‘remote_addr’
local.c:1296: error: ‘listen_ctx_t’ has no member named ‘timeout’
local.c:1297: error: ‘listen_ctx_t’ has no member named ‘iface’
local.c:1298: error: ‘listen_ctx_t’ has no member named ‘mptcp’
local.c:1301: error: storage size of ‘sigint_watcher’ isn’t known
local.c:1302: error: storage size of ‘sigterm_watcher’ isn’t known
local.c:1303: error: implicit declaration of function ‘ev_signal_init’
local.c:1303: error: ‘signal_cb’ undeclared (first use in this function)
local.c:1305: error: implicit declaration of function ‘ev_signal_start’
local.c:1305: error: ‘EV_DEFAULT’ undeclared (first use in this function)
local.c:1309: error: ‘ev_timer’ undeclared (first use in this function)
local.c:1309: error: expected ‘;’ before ‘parent_watcher’
local.c:1310: error: ‘parent_watcher’ undeclared (first use in this function)
local.c:1310: error: ‘parent_watcher_cb’ undeclared (first use in this function)
local.c:1311: error: implicit declaration of function ‘ev_timer_start’
local.c:1331: error: ‘listen_ctx_t’ has no member named ‘fd’
local.c:1333: error: ‘listen_ctx_t’ has no member named ‘io’
local.c:1333: error: ‘accept_cb’ undeclared (first use in this function)
local.c:1333: error: ‘EV_READ’ undeclared (first use in this function)
local.c:1334: error: implicit declaration of function ‘ev_io_start’
local.c:1334: error: ‘listen_ctx_t’ has no member named ‘io’
local.c:1361: error: implicit declaration of function ‘ev_run’
local.c:1368: error: implicit declaration of function ‘ev_io_stop’
local.c:1368: error: ‘listen_ctx_t’ has no member named ‘io’
local.c:1369: error: passing argument 1 of ‘free_connections’ from incompatible pointer type
local.c:233: note: expected ‘struct ev_loop *’ but argument is of type ‘struct ev_loop *’
local.c:1372: error: ‘listen_ctx_t’ has no member named ‘remote_addr’
local.c:1372: error: ‘listen_ctx_t’ has no member named ‘remote_addr’
local.c:1373: error: ‘listen_ctx_t’ has no member named ‘remote_addr’
local.c:1373: error: ‘listen_ctx_t’ has no member named ‘remote_addr’
local.c:1378: error: implicit declaration of function ‘ev_signal_stop’
local.c:1302: error: unused variable ‘sigterm_watcher’
local.c:1301: error: unused variable ‘sigint_watcher’
make[2]: *** [obfs_local-local.o] Error 1
make[2]: Leaving directory `/root/simple-obfs/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/simple-obfs'
make: *** [all] Error 2

**Comment by kimw** [comment]
It's caused by empty submodules. You need to read and follow README file.

```sh
git clone https://github.com/shadowsocks/simple-obfs.git
cd simple-obfs
git submodule update --init --recursive
./autogen.sh
./configure && make
sudo make install
```

**Comment by fhwo13** [comment]
已解决。

方法一：
“在 CentOS 6 下编译出现 error: ev.h: No such file or directory 错误时，原因如下：
CentOS 6 下 ev.h 位于 /usr/include/libev/ev.h，因此需要修改以下代码里关于 ev.h 路径定义的地方。
打开 src/local.h  和  src/server.h 两个文件，找到 #include <ev.h> 这一行，修改为 #include <libev/ev.h> 即可通过编译。”

方法二：
ln -s /usr/include/libev/ev.h ./src/ev.h
