### ISSUE TITLE
ERROR: plugin service exit unexpectedly

### ISSUE THREAD

**Issue by LisonFan** [shadowsocks/simple-obfs#33]
ss-server -A -u -c config.json

config.json
{
        "server":"0.0.0.0",
        "server_port":port,
        "local_address":"127.0.0.1",
        "local_port":1080,
        "password":"mypassword",
        "timeout":600,
        "method":"chacha20",
        "fast_open":false,
        "plugin":"obfs-server",
        "plugin_opts":"obfs=http"
}

最新版的 libev 和 obfs

**Comment by rogers0** [comment]
@LisonFan I guess it's the same issue as: https://github.com/shadowsocks/shadowsocks-libev/issues/1166#issuecomment-276902983
Please try the solution on that post.
