### ISSUE TITLE
加入failover参数后c#客户端连接失败

### ISSUE THREAD

**Issue by xiaojj** [shadowsocks/simple-obfs#46]
simle-obfs和ss-libev都是用的最新版。
C#用的是3.4.3

没加failover，C#版本连接没问题，加上后C#版本的ss连接不上。

**Comment by madeye** [comment]
It's expected. Failover means when obfscating fail, it will connect to the address instead of forwarding raw traffic.

**Comment by xiaojj** [comment]
明白，谢谢。
