### ISSUE TITLE
failover不兼容chrome和firefox

### ISSUE THREAD

**Issue by suikatomoki** [shadowsocks/simple-obfs#47]
ie和edeg正常
![qq 20170216212814](https://cloud.githubusercontent.com/assets/10336224/23023089/e14e85ca-f48e-11e6-9d57-90b5b3bb448a.png)
firefox和chrome异常
![qq 20170216212922](https://cloud.githubusercontent.com/assets/10336224/23023134/00ecc2ca-f48f-11e6-8246-fc231c3ca2aa.png)

使用的命令是：
obfs-server -s server_ip -p 443 --obfs tls -r 127.0.0.1:8388 --failover 127.0.0.1:8443
版本都是用的新版
web服务器是nginx

**Comment by madeye** [comment]
Try add `--obfs-host <host-name-set-in-your-client>` to your command line.

**Comment by madeye** [comment]
Also, try this 4cb4bb5

**Comment by suikatomoki** [comment]
@madeye Working now! Thanks.
