### ISSUE TITLE
Consider providing a docker build file?

### ISSUE THREAD

**Issue by longkai** [shadowsocks/simple-obfs#48]
The core project has docker build files which works pretty well and keep up with the release cycle. 

However, it lacks this plugin.

I suppose this one could be done by simply replace some scripts with that docker file. For a general usage, consider providing a docker build file or some hint in README?

**Comment by liaohuqiu** [comment]
https://hub.docker.com/r/liaohuqiu/simple-obfs/~/dockerfile/

**Comment by longkai** [comment]
@liaohuqiu thank you for sharing.

It turns out it could be done by simply adding some scripts with [that docker file](https://github.com/shadowsocks/shadowsocks-libev/blob/master/docker/alpine/Dockerfile). I've embed obfs and libev in one **single** docker image.

For anyone interested, you could find the Dockerfile in this [gist][https://gist.github.com/longkai/207ef3551fc77d371c1a68ea81db9c6b].

The usage is same as the [official repo docker](https://github.com/shadowsocks/shadowsocks-libev/tree/master/docker/alpine).

**NOTE**: OTA has been deprecated in recent version, changing your client setting if necessary.
