### ISSUE TITLE
服务端和客户端设置要完全一样吗？

### ISSUE THREAD

**Issue by azgh** [shadowsocks/simple-obfs#5]
On the client:
`obfs-local -s server_ip -p 8139 -l 1984 --obfs http --obfs-host www.baidu.com`
`ss-local -c config.json -s 127.0.0.1 -p 1984 -l 1080`
On the server:
`obfs-server -s server_ip -p 8139 --obfs http -r 127.0.0.1:8388`
`ss-server -c config.json -s 127.0.0.1 -p 8388`
服务端是否需要`--obfs-host`？
还有一个疑问`obfs-server`可以开多个端口吗？如果能怎么开？
谢谢

**Comment by suikatomoki** [comment]
不需要 host 只需要客户端指定
不可以 一个obfs-server进程只能对应一个端口

**Comment by azgh** [comment]
@suikatomoki 多谢了
