### ISSUE TITLE
若在ss-libev服务端的config添加obfs参数，则无法使用低于1024的端口

### ISSUE THREAD

**Issue by Aniark** [shadowsocks/simple-obfs#51]
例如：
{
    "server":"0.0.0.0",
    "server_port":443,
    "local_port":1080,
    "password":"1234",
    "timeout":60,
    "method":"chacha20-ietf-poly1305",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http"
}
这样的话，ss-libev便无法通过/etc/init.d/shadowsocks-libev start 或 systemctl start shadowsocks-libev启动；若通过ss-server后添加参数的方式，则可以启动，但客户端无法上网

若使用大于1024的端口，则能正常启动ss-libev，正常使用

如何能够在使用obfs的情况下使用低于1024的端口？

**Comment by hellofwy** [comment]
使用低于1024的端口需要更高权限。
请参考所用系统的权限怎么配置。
简单粗暴的话，以 root 用户运行。

**Comment by Aniark** [comment]
@hellofwy 默认就是root用户了，还是不行

**Comment by hellofwy** [comment]
需要修改启动文件内部的用户和用户组参数：

https://github.com/shadowsocks/shadowsocks-libev/blob/12c4344a420b230be8c5c286176081d4628c0eed/debian/shadowsocks-libev.service#L19

你也可以自己新建一个启动文件。

**Comment by Aniark** [comment]
@hellofwy 将User和Group的值都改为root了，还是不行
