### ISSUE TITLE
这个混淆能不能免流？

### ISSUE THREAD

**Issue by wupeng1211** [shadowsocks/simple-obfs#54]
混淆头标识后能不能免流？

**Comment by suikatomoki** [comment]
这个混淆不方便免流
不过你可以去搜索 “ssr 免流”

**Comment by wupeng1211** [comment]
@ @suikatomoki 这个不也是混淆头文件吗？那这个混淆只是加密传输莫

**Comment by suikatomoki** [comment]
@wupeng1211  simple-obfs的http混淆用的是websocket，不知道靠不靠谱，要不你实测一下吧

**Comment by lizardll** [comment]
实测免流成功，和ssr的simple-http模式效果一致
