### ISSUE TITLE
How can i let "plugin obfs-server" always be running?

### ISSUE THREAD

**Issue by yukeiyang** [shadowsocks/simple-obfs#59]
**I success to apply obfs server, but how can i let it always run?**

root@f:~# ss-server -c /etc/shadowsocks-libev/config.json --plugin obfs-server --plugin-opts "obfs=http"
 2017-03-10 01:10:15 INFO: plugin "obfs-server" enabled
 2017-03-10 01:10:15 INFO: initializing ciphers... chacha20-ietf
 2017-03-10 01:10:15 INFO: tcp server listening at 127.0.0.1:33999
 2017-03-10 01:10:15 INFO: running from root user
 2017-03-10 01:10:15 [simple-obfs] INFO: obfuscating enabled
 2017-03-10 01:10:15 [simple-obfs] INFO: tcp port reuse enabled
 2017-03-10 01:10:15 [simple-obfs] INFO: listening at 0.0.0.0:443
 2017-03-10 01:10:15 [simple-obfs] INFO: running from root user

**Or, another way, how can i let it run when the server boot & reboot?**

**Comment by liyiecho** [comment]
modify the config.json like this:
```
{
    "server":"",
    "server_port":,
    "local_port":1080,
    "password":"",
    "timeout":60,
    "method":"",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http"
}
```

**Comment by yukeiyang** [comment]
@liyiecho, Absolutely I set the config.json same like you said. But simple-obfs not run after boot or  reboot yet. so, i submitted this issue as you see. And thanks for your patient. 

Server：Ubuntu 16.10
Client：Openwrt 15.05 on xiaomi-mini router
Simple-obfs installed in the server and client yet.

**If run：**
`ss-server -c /etc/shadowsocks-libev/config.json --plugin obfs-server --plugin-opts "obfs=http"`
Simple-obfs will be run success in the server, and client will be succeed. 

**But if only leave the config same like this:**
```
{
    "server":"",
    "server_port":,
    "local_port":1080,
    "password":"",
    "timeout":60,
    "method":"",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http"
}
```
Simple-obfs will not run, and client will not be success.

I enable shadowsocks-libev in server end, with 
```
$ sudo /etc/init.d/shadowsocks-libev start   
$ sudo systemctl start shadowsocks-libev 

```

How can i enable obfs in server end too?

**Comment by yukeiyang** [comment]
**obfs seems enabled. **

root@f:~# /etc/init.d/shadowsocks-libev status -l
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Fri 2017-03-10 16:29:43 CST; 1h 31min ago
     Docs: man:shadowsocks-libev(8)
  Process: 31185 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=0/SUCCESS)
 Main PID: 31185 (code=exited, status=0/SUCCESS)

Mar 10 16:29:43 f systemd[1]: Started Shadowsocks-libev Default Server Service.
Mar 10 16:29:43 f ss-server[31185]:  2017-03-10 16:29:43 INFO: plugin "obfs-server" enabled
Mar 10 16:29:43 f ss-server[31185]:  2017-03-10 16:29:43 INFO: UDP relay enabled
Mar 10 16:29:43 f ss-server[31185]:  2017-03-10 16:29:43 INFO: initializing ciphers... chacha20-ietf
Mar 10 16:29:43 f ss-server[31185]:  2017-03-10 16:29:43 INFO: tcp server listening at 127.0.0.1:46547
Mar 10 16:29:43 f ss-server[31185]:  2017-03-10 16:29:43 INFO: udp server listening at 0.0.0.0:443
Mar 10 16:29:43 f ss-server[31185]:  2017-03-10 16:29:43 [simple-obfs] INFO: obfuscating enabled

**Comment by liyiecho** [comment]
After you modify the config.json , you should use the command `sudo systemctl restart shadowsocks-libev` to restart shadowsocks and the  command `sudo systemctl status shadowsocks-libev` to see its status.

**Comment by yukeiyang** [comment]
root@f:~# sudo systemctl restart shadowsocks-libev
root@f:~# systemctl status shadowsocks-libev
● shadowsocks-libev.service - Shadowsocks-libev Default S   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.   Active: inactive (dead) since Fri 2017-03-10 18:43:46      Docs: man:shadowsocks-libev(8)
  Process: 1026 ExecStart=/usr/bin/ss-server -c $CONFFILE Main PID: 1026 (code=exited, status=0/SUCCESS)

Mar 10 18:43:46 f ss-server[1026]:  2017-03-10 18:43:46 IMar 10 18:43:46 f ss-server[1026]:  2017-03-10 18:43:46 IMar 10 18:43:46 f ss-server[1026]:  2017-03-10 18:43:46 IMar 10 18:43:46 f ss-server[1026]:  2017-03-10 18:43:46 IMar 10 18:43:46 f ss-server[1026]:  2017-03-10 18:43:46 IMar 10 18:43:46 f ss-server[1026]:  2017-03-10 18:43:46 [Mar 10 18:43:46 f ss-server[1026]:  2017-03-10 18:43:46 [Mar 10 18:43:46 f ss-server[1026]:  2017-03-10 18:43:46 [Mar 10 18:43:46 f ss-server[1026]:  2017-03-10 18:43:46 [Mar 10 18:43:46 f ss-server[1026]:  2017-03-10 18:43:46 [lines 1-17/17 (END)

**Comment by yukeiyang** [comment]
@liyiecho , awesome. when I adjust the port more than 1024, it success.
thanks a lot.
