### ISSUE TITLE
getpeername: Transport endpoint is not connected

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/simple-obfs#7]
```
# obfs-server -s 0.0.0.0 -p 8139 --obfs http -r 127.0.0.1:8388
$ obfs-local -s SERVER_IP -p 8139 -l 1984 --obfs http --obfs-host www.baidu.com
```

ss-local gets `getpeername: Transport endpoint is not connected` all the time after adding `-p 1984`. :confused:

**Comment by madeye** [comment]
It looks weird. What's your command line for ss-local?

**Comment by Mygod** [comment]
`ss-local -c config.json --fast-open -l 1080 -p 1984`

**Comment by madeye** [comment]
What about removing `--fast-open`?

**Comment by Mygod** [comment]
Okay I have just disabled fast open everywhere and nothing has changed.

**Comment by madeye** [comment]
Hmm, what's your config.json?

**Comment by Mygod** [comment]
```
{
    "server":"0.0.0.0",
    "server_port":8388,
    "local_port":1080,
    "password":"*removed*",
    "timeout":60,
    "method":"chacha20",
    "auth":true
}
```

**Comment by madeye** [comment]
For `ss-local`, `server` should be `127.0.0.1`?

**Comment by Mygod** [comment]
Oh wait I connected to the wrong server! Silly me! :rofl: 

There's no more `Transport endpoint is not connected` however I'm still getting `ERR_CONNECTION_RESET`. There are no error logs anywhere. Hmm...

**Comment by Mygod** [comment]
Hmm yeah server should be 127.0.0.1. Now everything works...

**Comment by madeye** [comment]
Great! It turns out to be not another bug. 😌
