### ISSUE TITLE
autogen.sh failed on alpinelinux

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/simple-obfs#76]
>>> simple-obfs: Unpacking /var/cache/distfiles/simple-obfs-0.0.3.tar.gz...
configure.ac:19: error: possibly undefined macro: AC_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:20: error: possibly undefined macro: AC_DISABLE_SHARED
configure.ac:44: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf failed with exit status: 1
>>> ERROR: simple-obfs: all failed

**Comment by lrinQVQ** [comment]
try this dependencies:https://github.com/lrinQVQ/simple-obfs/commit/7af8aaa53fbda0556d86cf3777e70989d9548b15
