### ISSUE TITLE
0.0.3无法使用copr打包rpm文件，0.0.2可以

### ISSUE THREAD

**Issue by Amonhuz** [shadowsocks/simple-obfs#79]
你好，
之前使用copr打包rpm文件安装，0.0.2版本可以成功打包，0.0.3一直失败，对比了两个源码包的内容0.0.3少了一些库，请问是这个原因吗？
该如何操作，才能使0.0.3版本打包成功呢？

谢谢！

**Comment by Amonhuz** [comment]
已解决

**Comment by debiansid** [comment]
能提供下载么
