### ISSUE TITLE
Obfuscation makes it easier to detect?

### ISSUE THREAD

**Issue by heshiming** [shadowsocks/simple-obfs#81]
The logic of obfuscation is mainly to fool one kind of automated detection tool with lower intelligence. If that tool was smart enough to verify by calling just `curl -v http://somehost` (where port 80 is hosted by simple-obfs), it'll get consistently:

    * Curl_http_done: called premature == 0
    * Empty reply from server
    * Connection #0 to host somehost left intact

The server doesn't return a status code or any headers for that matter. If you go ahead and try with `-x HEAD` or even `-x PUT`, you pretty much understand it's a fake HTTP server. Even that alone is not proof of guilt. Having large, high entropy traffic through a fake HTTP server can definitely lead to suspicion.

Bundling a cert and behave as TLS could be another frivolous step to fool the same detection tool.

Does this defeat the purpose of obfuscation?

**Comment by madeye** [comment]
https://github.com/shadowsocks/simple-obfs/issues/32
https://github.com/shadowsocks/simple-obfs/pull/74

Use `--failover` option or run simple-obfs behind a reverse proxy.

**Comment by heshiming** [comment]
Great. I didn't realize the `--failover` option was for this purpose.

For future reference, `--failover` option is to pass down HTTP requests which `obfs-server` itself isn't going to handle (i.e. a real HTTP request).

To set this up, let's say that you have `obfs-local ... --obfs-host al.vod.tv.itc.cn ...`. With an nginx reverse proxy, you can actually pass the requests to that host. Example configuration:

    server {
        listen 127.0.0.1:8080;
        location / {
            proxy_pass http://al.vod.tv.itc.cn;
        }
    }

Use `--failover 127.0.0.1:8080` for the example configuration.

One caveat, the target will know your server IP address. So consider benign and low profile targets.
