### ISSUE TITLE
有计划支持Mac吗

### ISSUE THREAD

**Issue by lizhaode** [shadowsocks/simple-obfs#83]
好像目前只有Linux才行吧，Mac能编译运行吗？

**Comment by pexcn** [comment]
可以。

**Comment by lizhaode** [comment]
@pexcn 应该怎么编译呢？需要哪些依赖？

**Comment by pexcn** [comment]
https://github.com/shadowsocks/simple-obfs#build 这里不是讲得很清楚吗？

**Comment by lizhaode** [comment]
@pexcn Mac也是装这些工具吗？

**Comment by xavierzz** [comment]
安在mac上做什么？不都是按在服务端上么？

**Comment by pexcn** [comment]
@lizhaode `For Unix-like systems...`

**Comment by lizhaode** [comment]
@xavierzz 本地也需要，不然服务端设置了obfs之后，本地用不了哎

**Comment by xavierzz** [comment]
@lizhaode  哦 这样 如果用了surge就不用了

**Comment by lizhaode** [comment]
@xavierzz surge支持这个？

**Comment by xavierzz** [comment]
@lizhaode 支持呀，服务端配好后，surge再配一下就可以了。

**Comment by vinewx** [comment]
brew install simple-obfs

**Comment by B44ST** [comment]
brew install simple-obfs 之后只能用 obfs-local 一直提示 -bash: ss-local: command not found

**Comment by vinewx** [comment]
@B44ST 最近写了一个一键脚本，你可以试试看 https://github.com/vinewx/SRK

**Comment by zpole** [comment]
@B44ST brew install shadowsocks-libev
