### ISSUE TITLE
It neets more than 64m memory when I make?

### ISSUE THREAD

**Issue by haruhitamako** [shadowsocks/simple-obfs#85]
/usr/bin/xmlto: line 580: 12420 Killed                  "/usr/bin/xsltproc" --nonet --xinclude --param passivetex.extensions '1' -o "/tmp/xmlto.Z3nU58/obfs-local.proc" "/tmp/xmlto-xsl.IDYbdh" "/root/simple-obfs/doc/obfs-local.xml"
Makefile:563: recipe for target 'obfs-local.1' failed

**Comment by dutonttie** [comment]
try  ./configure --prefix=/usr --disable-documentation

haruhitamako <notifications@github.com>于2017年7月31日周一 16:50写道：

**Comment by haruhitamako** [comment]
@dutonttie yes,that's ok !thank you
