### ISSUE TITLE
支持使用homebrew下载

### ISSUE THREAD

**Issue by Thomas4949** [shadowsocks/simple-obfs#86]
受限于个人水平，我在Mac上编译程序远不如在Linux上顺畅。个人感觉下载依赖Mac就要比Linux麻烦很多。
如果可以，希望simple-obfs插件能够支持使用Homebrew下载安装。
事实上，我很希望这个插件能够和shadowsocks-libev捆绑在一起下载，用不用是另一回事，反正它的体积也不大，基本不占硬盘。

**Comment by lizhaode** [comment]
现在已经可以用homebrew来安装了，但是我安装了以后，运行有问题

**Comment by Thomas4949** [comment]
请问使用Homebrew安装我应该使用什么名称？
simple-obfs吗？

2017年8月1日 +0800 16:54 lizhaode <notifications@github.com>，写道：

**Comment by lizhaode** [comment]
是的，你可以用brew info查看一下

**Comment by Thomas4949** [comment]
谢谢，我下载好了。
而且，我这里运行目前为止到还没什么问题。

**Comment by lizhaode** [comment]
#87 这个是我遇到的问题，不知道你那边有没有。你是直接从命令行启动还是配置文件？

**Comment by Thomas4949** [comment]
嗯，我之前是用命令行启动的。刚才用配置文件试了下，确实有和你一样的问题。

**Comment by lizhaode** [comment]
你能贴出来你的服务端和客户端的配置文件吗，我对比一下，看看是不是我哪配置有问题，我开了混淆就连不上服务器，不开就正常

**Comment by Thomas4949** [comment]
其实我这里情况也有点搞不明白。
怎么说呢？
其实，我的服务端的日志文件里和你一样有报错（一摸一样的报错），但我的客户端打开后是可以通过代理正常访问外网的。
请问你在服务端报错的情况下可以通过代理正常上网吗？

**Comment by lizhaode** [comment]
奇怪，我改成用配置文件开混淆，竟然正常了，但是直接用命令行还是会出错，不知道是哪里出了问题

**Comment by Thomas4949** [comment]
你原来使用命令行会出错吗？
看 #87 的标题，似乎你原来用命令行没事啊。

**Comment by lizhaode** [comment]
用命令行出错是连接服务器出错，用配置文件之前是因为加载obfs插件出错
