### ISSUE TITLE
tls混淆服务端混淆域名设定

### ISSUE THREAD

**Issue by Thomas4949** [shadowsocks/simple-obfs#88]
对于http混淆，只要在客户端指定混淆域名就可以了。
那么，tls混淆是否需要在服务端指定与客户端一样的混淆域名？还是与http混淆一样，只需要在客户端填写即可？

**Comment by pexcn** [comment]
客服 Max Witten 很高兴为您服务：
可以参照：https://github.com/shadowsocks/simple-obfs/blob/master/doc/obfs-local.asciidoc
