### ISSUE TITLE
obfs-server doesn't work when using V2RAY

### ISSUE THREAD

**Issue by ticonci** [shadowsocks/simple-obfs#89]
Hi Max,
    i am running this **obfs-server -s 0.0.0.0 -p 443 --obfs tls -r 127.0.0.1:1443 --failover 127.0.0.1:2443 -v** in the VM, **ss-sever is listening on 127.0.0.1:1443**, and **nginx is listening on 127.0.0.1:2443**.
    And the nginx is running as a https and websocket server which will deal with the normal https and v2ray traffic. On the v2ray client side, i added a TLS layer to the traffic. that's where the problem comes from.
    The obfs-server redirect all the v2ray traffic to the 127.0.0.1:1443.
     Is it possbile to fix this?  thx very much

**Comment by madeye** [comment]
Try deploy obfs-server behind nginx:

https://github.com/shadowsocks/simple-obfs/pull/74

**Comment by FC-Radio** [comment]
有個問題，obfs只支援libev？
