### ISSUE TITLE
libc-ares replace libudns

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/simple-obfs#98]
when you guys do it for simple-obfs?

**Comment by lrinQVQ** [comment]
I try replace libudns to libc-ares in https://github.com/lrinQVQ/simple-obfs/commit/63507530524ac011c8fb380c7b8fb7904769267a
it's work in my server
I use shadowsocks-libev 3.0.8
and base https://github.com/shadowsocks/shadowsocks-libev/commit/ede744ae7c79dfc91e93c3eca31b00fd6f951fc6 to copy and paster :)
If there is a problem,please tell me,thanks~

**Comment by debiansid** [comment]
Would you please make a pull request here? Thanks.
I will try it out later

**Comment by madeye** [comment]
@lrinQVQ Cool! What about a pull request?

**Comment by lrinQVQ** [comment]
@madeye I create a pull request now~~

**Comment by lrinQVQ** [comment]
0.0 and fix Travis Config in https://github.com/shadowsocks/simple-obfs/pull/100/commits/c267683ec2f99de9c4315e93573bdfd88602bd49
