### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by hybtoy** [shadowsocks/simple-obfs#99]
Hello, 

How to use simple-obfs on Windows with Shadowsocks for Windows?

https://github.com/shadowsocks/shadowsocks-windows

Thanks.

**Comment by joshua-kfbb** [comment]
For me, I just tried to put a [pre-compiled binary](https://github.com/imgk/simple-obfs-Cygwin/releases) of simple-obfs client for windows in the same directory as the shadowsocks executable, and config the server as following:

![image](https://user-images.githubusercontent.com/22837904/30200395-43782692-94a9-11e7-950b-85851422406d.png)

And it works.

**Comment by hybtoy** [comment]
@joshua-kfbb not working for me. 
Could you pack your ss folder to archive and send to me without your server config, please? 
Or tell me how to do it step by step. 
Thanks.

**Comment by joshua-kfbb** [comment]
Clone the repo, build it and try. The latest release doesn't support plugins so far.



在 hybtoy <notifications@github.com>，2017年9月8日 下午6:09写道：

@joshua-kfbb<https://github.com/joshua-kfbb> not working for me.
Could you pack your ss folder to archive and send to me without your server config, please?
Or tell me how to do it step by step.
Thanks.

**Comment by hybtoy** [comment]
@joshua-kfbb So which release I need to use to make it work with plugins?

**Comment by hybtoy** [comment]
@joshua-kfbb And why I need to clone it if they are .exe files?

**Comment by joshua-kfbb** [comment]
Because the executables are not up to date.



在 hybtoy <notifications@github.com>，2017年9月8日 下午6:15写道：

@joshua-kfbb<https://github.com/joshua-kfbb> And why I need to clone it if they are .exe files?

**Comment by hybtoy** [comment]
@joshua-kfbb Compile it on Windows?

**Comment by joshua-kfbb** [comment]
if you mean shadowsocks itself, yes. you may need visual studio to do so.
for obfs plugin, please refer my first reply for the binary.



在 hybtoy <notifications@github.com>，2017年9月8日 下午6:22写道：

@joshua-kfbb<https://github.com/joshua-kfbb> Compile it on Windows?
